config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :movies do
       member do
         post :join
         post :quit
       end
    resources :reviews
  end

  namespace :account do
    resources :movies
    resources :reviews
  end
  root 'movies#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true
  belongs_to :user
  has_many :reviews
  has_many :movie_relationships
  has_many :members, through: :movie_relationships, source: :user
end

app/models/movie_relationship.rb
class MovieRelationship < ApplicationRecord
  belongs_to :movie
  belongs_to :user
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :movie
  validates :content, presence: true
  scope :recent, -> { order("created_at DESC")}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :movies
  has_many :reviews
  has_many :movie_relationships
  has_many :participated_movies, :through => :movie_relationships, :source => :movie

  def is_member_of?(movie)
    participated_movies.include?(movie)
  end

  def join!(movie)
    participated_movies << movie
  end

  def quit!(movie)
    participated_movies.delete(movie)
  end
      
end

app/controllers/account/movies_controller.rb
class Account::MoviesController < ApplicationController
  before_action :authenticate_user!

  def index
    @movies = current_user.participated_movies
  end  
end

app/controllers/account/reviews_controller.rb
class Account::ReviewsController < ApplicationController
  before_action :authenticate_user!

  def index
    @reviews = current_user.reviews.recent.paginate(:page => params[:page], :per_page => 5)
  end

  def edit
    @movie = Moive.find(params[:movie_id])
    @review = Rview.find(params[:id])
  end

  def updated
    @movie = Movie.find(params[:movie_id])
    @review = Review.find(params[:id])
    if @review.update(review_params)
      redirect_to reviews_path(@review), notice: "Updated review"
    else
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:movie_id])
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to reviews_path(@review), alert: "Review deleted"
  end


  private

  def review_params
    params.require(:review).permit(:content)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :destroy]
  before_action :find_movie_and_check_permission, only: [:edit, :update, :destroy,:join, :quit]
  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
    @reviews = @movie.reviews.recent.paginate(:page => params[:page], :per_page => 5)
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    @movie.user = current_user

    if @movie.save
      current_user.join!(@moive)
      redirect_to movies_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @movie.update(movie_params)
      redirect_to movies_path, notice: "Updated success"
    else
      render :edit
    end
  end

  def destroy
    @movie.destroy
    redirect_to movies_path, alert: "Movie deleted"
  end

  def join
    @movie = Movie.find(params[:id])

    if !current_user.is_member_of?(@movie)
      current_user.join!(@movie)
      flash[:notice] = "收藏本影片成功！"
    else
      flash[:warning] = "你已经收藏过本影片了！"
    end

    redirect_to movie_path(@movie)
  end

  def quit
    @movie = Movie.find(params[:id])

    if current_user.is_member_of?(@movie)
      current_user.quit!(@movie)
      flash[:alert] = "已取消收藏本影片！"
    else
      flash[:warning] = "你都没有收藏过本影片，怎么能取消呢"
    end

    redirect_to movie_path(@movie)
  end


  private

  def movie_params
    params.require(:movie).permit(:title, :description)
  end

  def find_movie_and_check_permission
    @movie = Movie.find(params[:id])

    if current_user != @movie.user
      redirect_to root_path, alert: "You have no permission."
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, :only => [:new, :create]

  def new
    @movie = Movie.find(params[:movie_id])
    @review = Review.new
  end

  def create
    @movie = Movie.find(params[:movie_id])
    @review = Review.new(review_params)
    @review.movie = @movie
    @review.user = current_user
    if @review.save
      redirect_to movie_path(@movie)
    else
      render :new
    end
  end

  def edit
    @movie = Movie.find(params[:movie_id])
    @review = Review.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:movie_id])
    @review = Review.find(params[:id])
    if @review.update(review_params)
      redirect_to account_reviews_path(@review), notice: "Updated review"
    else
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:movie_id])
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to account_reviews_path(@review), alert: "Review deleted"
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    flash[:notice] = "早安！你好！"
  end
end

app/helpers/account/movies_helper.rb
module Account::MoviesHelper
end

app/helpers/account/reviews_helper.rb
module Account::ReviewsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice", "warning"
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
  def render_movie_description(movie)
    simple_format(movie.description)
  end  
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
    <p class="text-center">Copyright ©2017 Rails101
        <br>Design by
        <a href="http://courses.growthschool.com/courses/rails-101/" target=_new>xdite</a>
    </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="/">Rails 101</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
              <% if !current_user %>
                  <li><%= link_to("注册", new_user_registration_path) %> </li>
                  <li><%= link_to("登录", new_user_session_path) %></li>
                <% else %>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Hi!, <%= current_user.email %>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li> <%= link_to("My Movies", account_movies_path) %></li>
                        <li> <%= link_to("My Reviews", account_reviews_path) %></li>
                        <li class="divider"> </li>
                        <li> <%= link_to("退出", destroy_user_session_path, method: :delete) %> </li>
                    </ul>
                  </li>
                <% end %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails107</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
             <%= render "common/navbar" %>
             <%= render "common/flashes" %>
             <%= yield %>
    </div>

    <%= render "common/footer" %>

  </body>
</html>

app/views/movies/_form.html.erb
<%= simple_form_for @movie do |f| %>
  <div class="form-movie">
    <%= f.input :title, input_html: { class: "form-control"} %>
    <%= f.input :description, input_html: { class: "form-control"} %>
  </div>
  <%= f.submit "Submit", class: "btn btn-primary", data: { disable_with: "Submiting..." } %>
<% end %>

app/views/movies/_movie_item.html.erb
<tr>
  <td><%= link_to(movie.title, movie_path(movie)) %></td>
  <td><%= render_movie_description(movie) %><td>
  <td><%= movie.user.email %></td>
  <td>
      <% if current_user && current_user == movie.user %>
      <%= link_to("Edit", edit_movie_path(movie), class: "btn btn-sm btn-default")%>
      <%= link_to("Delete", movie_path(movie), class: "btn btn-sm btn-default",
                    method: :delete, data: { confirm: "Are you sure?" } )%>
      <% end %>
  </td>
</tr>

app/views/movies/edit.html.erb
<div class="col-md-4 col-md-offset-4">
  <h2>修改</h2>

  <hr>
  <%= render "form" %>
</div>  

app/views/movies/index.html.erb
<div class="col-md-12">
  <div class="movie">
    <%= link_to("点评电影", new_movie_path, class: "btn btn-primary pull-right") %>
  </div>
  <table class="table table-hover">
    <thead>
      <tr>

        <td>影片</td>
        <td>剧情简介</td>
        <td>创建者</td>
      </tr>
    </thead>
    <tbody>
      <%= render :partial => "movie_item", :collection => @movies, :as => :movie %>
    </tbody>
  </table>
</div>

app/views/movies/new.html.erb
<div class="col-md-4 col-md-offset-4">
  <h2>新增影片</h2>

  <hr>
  <%= render "form" %>
</div>

app/views/movies/show.html.erb
<div class="col-md-12">
  <div class="movie">

    <span class="pull-right">
      <% if current_user && current_user.is_member_of?(@movie) %>
      <%= link_to("Write a Review", new_movie_review_path(@movie), class: "btn btn-default left-right") %>
        <label class="label label-success"> 已收藏本影片 </label>
             <%= link_to("Quit Movie", quit_movie_path(@movie), method: :review, class: "btn btn-default") %>
      <% else %>
        <label class="label label-warning"> 未收藏本影片</laber>
             <%= link_to("Join Movie", join_movie_path(@movie), method: :review, class: "btn btn-default") %>
      <% end %>
    </span>


    <% if current_user && current_user == @movie.user %>
       <%= link_to("Edit", edit_movie_path(@movie), class: "btn btn-primary pull-right") %>
    <% end %>
  </div>
  <h2><%= @movie.title %></h2>
  <p><%= @movie.description %></p>

  <table class="table">
    <thead>
      <tr>
        <th>影片内容</th>
        <th>创建者</th>
        <th>创建时间</th>
      </tr>
    </thead>
    <tbody>
      <% @reviews.each do |review| %>
        <tr>
          <td><%= review.content %></td>
          <td><%= review.user.email %></td>
          <td><%= review.created_at %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="text-center">
      <%= will_paginate @reviews %>
  </div>

</div>

app/views/reviews/edit.html.erb
<h2 class="text-center">新建影评</h2>

<div class="col-md-4 col-md-offset-4">
   <%= simple_form_for [@movie,@review] do |f| %>
    <div class="form-movie">
      <%= f.input :content, input_html: { class: "form-control"} %>
    </div>
    <div class="form-actions">
      <%= f.submit "Submit", disable_with: "Submiting...", class: "btn btn-primary"%>
    </div>
  <% end %>
</div>

app/views/reviews/new.html.erb
<h2 class="text-center">新建影评</h2>

<div class="col-md-4 col-md-offset-4">
   <%= simple_form_for [@movie,@review] do |f| %>
    <div class="form-movie">
      <%= f.input :content, input_html: { class: "form-control"} %>
    </div>
    <div class="form-actions">
      <%= f.submit "Submit", disable_with: "Submiting...", class: "btn btn-primary"%>
    </div>
  <% end %>
</div>

app/views/welcome/index.html.erb
<h1> Hello World! </h1>